### ISSUE TITLE
ToDo: Nuevo comando help 

### ISSUE THREAD

**Issue by Phamzito** [TheHuskyBot/Husky#14]
Crear un nuevo comando help mas cómodo.
- Mostrando categorías
- Ayuda para comando individuales

**Comment by gatomo-oficial** [comment]
oc me da igual xd

**Comment by gatomo-oficial** [comment]
q
es q m eaburro

**Comment by gatomo-oficial** [comment]
pregunta
que es WIP? de eso de las etiketas

**Comment by Phamzito** [comment]
es como algo beta xd

**Comment by gatomo-oficial** [comment]
Ah oc :v
