### ISSUE TITLE
Contributors

### ISSUE THREAD

**Issue by Phamzito** [TheHuskyBot/Husky#15]
@all-contributors please add @Phamzito for code, doc, bug, review and userTesting

**Comment by Phamzito** [comment]
@all-contributors please add @Phamzito for code, doc, bug, review and userTesting

**Comment by Phamzito** [comment]
@all-contributors please add @Phamzito for code, doc and bug

**Comment by Phamzito** [comment]
@all-contributors please add @gatomo-oficial for code, doc and bug

**Comment by gatomo-oficial** [comment]
Y ese bot?

**Comment by Phamzito** [comment]
el bot de contribuciones
